[package]
name = "axum-template"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = ""
homepage = "https://github.com/Altair-Bueno/axum-template"
repository = "https://github.com/Altair-Bueno/axum-template"
readme = "README.md"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.57"
axum = { version = "0.5.13", features = ["matched-path"] }
serde = "1.0.142"
thiserror = "1.0.32"
tera = { version = "1.16.0", optional = true }
tower-layer = "0.3.1"
futures = "0.3.21"
tower-http = { version = "0.3.4", features = ["add-extension"] }
handlebars = { version = "4.3.3", optional = true }
tower-service = "0.3.2"
tinytemplate = { version = "1.2.1", optional = true }

[dev-dependencies]
tokio = { version = "1.20.1", features = ["full"] }
serde = { version = "1", features= ["derive"]}
tower-http = { version = "0.3.4", features = ["full"] }
tower = { version = "0.4.13", features = ["full"] }

[[example]]
name = "tera"
required-features=["tera"]

[[example]]
name = "handlebars"
required-features = ["handlebars"]
